// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 480);
    lv_obj_set_height(ui_Container1, 480);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LightArc = lv_arc_create(ui_Container1);
    lv_obj_set_width(ui_LightArc, 465);
    lv_obj_set_height(ui_LightArc, 465);
    lv_obj_set_x(ui_LightArc, 16);
    lv_obj_set_y(ui_LightArc, -26);
    lv_obj_set_align(ui_LightArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_LightArc, 50);


    ui_debug1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_debug1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_debug1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_debug1, -7);
    lv_obj_set_y(ui_debug1, -72);
    lv_obj_set_align(ui_debug1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_debug1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_debug2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_debug2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_debug2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_debug2, -7);
    lv_obj_set_y(ui_debug2, -3);
    lv_obj_set_align(ui_debug2, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_debug2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_LightArc, ui_event_LightArc, LV_EVENT_ALL, NULL);

}
